app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from .import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

class Users(UserMixin,db.Model):
    __tablename__='users'

    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(250),index=True)
    email=db.Column(db.String(250),unique=True,index=True)
    pass_secure=db.Column(db.String(250))
    profile=db.Column(db.String(250))
    about=db.Column(db.String(250))
    occupation=db.Column(db.String(250))

    @property
    def password(self):
        raise AttributeError("You can not read this")

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f"User {self.username}"

class Blogs(db.Model):
    __tablename__='blogs'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String())
    body=db.Column(db.String())

class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    email=db.Column(db.String())
    username=db.Column(db.String())
    comment=db.Column(db.String())
    blog_id=db.Column(db.Integer)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    
    def save_comments(self):
        db.session.add(self);
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments=Comments.query.filter_by(blog_id=id).all()
        return comments

class Quote:
    def __init__(self,quote,author):
        self.quote=quote
        self.author=author

class Role(db.Model):
    __tablename__='roles'
    id=db.Column(db.Integer,primary_key=True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,ValidationError,BooleanField,TextAreaField
from wtforms.validators import Required,Email,EqualTo

class CommentForm(FlaskForm):
    email=StringField('Your email ',validators=[Required(),Email()])
    name=StringField("Your name",validators=[Required()])
    comment=TextAreaField("Comment",validators=[Required()])
    submit=SubmitField("Submit")

class AdminBlog(FlaskForm):

    title=StringField("Title",validators=[Required()])
    body=TextAreaField("Blog Body")
    submit=SubmitField("Submit")

class DeleteBlog(FlaskForm):
    delete=SubmitField("Delete this Blog")

class DeleteComment(FlaskForm):
    delete1=SubmitField("Delete")

class UpdateProfile(FlaskForm):
    about=TextAreaField("Tell us about you ",validators=[Required()])
    occupation=StringField("What is you current occupation",validators=[Required()])
    submit=SubmitField("Save")

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_simplemde import SimpleMDE
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos=UploadSet('photos',IMAGES)

mail=Mail()
simplemde=SimpleMDE()
login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
db=SQLAlchemy()
bootstrap=Bootstrap()
def create_app(config_name):

    app=Flask(__name__)
    app.config.from_object(config_options[config_name])
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simplemde.init_app(app)
    mail.init_app(app)
    configure_uploads(app,photos)

    from .request import configure_request
    configure_request(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint

main=Blueprint("main",__name__)

from . import views,forms,errors

app/main/views.py
from . import main
from flask import render_template,redirect,url_for,flash,request,abort
from .forms import CommentForm,AdminBlog,DeleteBlog,DeleteComment,UpdateProfile
from .. import db,photos
import markdown2
from ..models import Blogs,Comments,Users
from ..request import get_quote
from ..email import mail_message



@main.route("/",methods=['POST','GET'])
def index():
    quote=get_quote()
    title="Blog"
    message="WELCOME"
    blogs=Blogs.query.all()
    top_blog=Blogs.query.all()
    top_blog.reverse()
    topBlog=top_blog[0:1]
    commento=Comments.query.filter_by(blog_id=500).all()
    form = CommentForm()
    if form.validate_on_submit():
        comments=Comments(blog_id=500,email=form.email.data,username=form.name.data,comment=form.comment.data)
        comments.save_comments()
        return redirect(url_for('main.index'))
    return render_template("index.html",commento=commento,topBlog=topBlog,quote=quote,message=message,title=title,comments=form,blogs=blogs)

@main.route("/new_blog",methods=["POST","GET"])
def new_blog():
    
    emails=Comments.query.all()
    all_emails=[]
    for emal in emails:
        all_emails.append(emal.email)


    form=AdminBlog()
    if form.validate_on_submit():
        blog=Blogs(title=form.title.data,body=form.body.data)
        db.session.add(blog)
        db.session.commit()
        mail_message("Hello A new Blog has been posted","email/welcome_user","")
        return redirect(url_for('main.index'))

    title="Write a blog"
    return render_template("new_blog.html",title=title,newBlog=form,all_emails=all_emails)

@main.route("/read_blog/title/<int:id>/",methods=['GET','POST'])
def read_blog(id):
    blog_id=id
    title="Blog"
    message="Welcome to my Blog"
    blog=Blogs.query.filter_by(id=id).first()
    blogs=Blogs.query.all()
    data=blog.title
    form = CommentForm()

    if form.validate_on_submit():
        comments=Comments(blog_id=id,email=form.email.data,username=form.name.data,comment=form.comment.data)
        comments.save_comments()
        return redirect(url_for('main.read_blog',id=blog_id))



    format_blog=markdown2.markdown(blog.body,extras=["code-friendly", "fenced-code-blocks"])

    blog_comment=Comments.query.filter_by(blog_id=id).all()


    del_form=DeleteBlog()
    dele=Blogs.query.filter_by(id=id).first()
    if del_form.validate_on_submit():

        db.session.delete(dele)
        db.session.commit()
        
        return redirect(url_for('main.index'))



    del_comment=DeleteComment()

    if del_comment.validate_on_submit():
        dele_com=Comments.query.filter_by(blog_id=id).first()
        db.session.delete(dele_com)
        db.session.commit()

        return redirect(url_for('main.read_blog',id=blog_id))



    return render_template("read_blog.html",deleform=del_form,data=data,blogComment=blog_comment,format_blog=format_blog,message=message,title=title,comments=form,blogs=blogs,id=id,del_comment=del_comment)

#profile picture

@main.route("/profile/<uname>")
def profile(uname):
    user=Users.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html",user=user)

@main.route("/profile/<uname>/update",methods=['GET','POST'])
def update_profile(uname):
    user=Users.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    form =UpdateProfile()
    if form.validate_on_submit():
        user.about=form.about.data
        user.occupation=form.occupation.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for(".profile",uname=user.username))

    return render_template("profile/update.html",form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
def update_pic(uname):
    user = Users.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile= path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{%extends 'bootstrap/base.html'%}
{%block navbar%}
{%include 'navbar.html'%}
{%endblock%}
{%block content%}

{%block styles%}
{{ simplemde.css}}
{{ simplemde.js }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/mdb.css')}}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<link rel="icon" href="/static/photos/author.jpg">
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.js')}}"></script>
<script src="{{ url_for('static', filename='js/mdb.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="{{ url_for('static', filename='js/main.js')}}"></script>
{%endblock%}
{%endblock%}

app/templates/index.html
{%extends 'base.html'%}
{%import "bootstrap/wtf.html" as wtf%}
{%block content%}

<!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


<div id="bac" class="jumbotron">
  <!-- <div class="bg-image"><img src="/static/photos/author.jpg"> -->
    <h1>{{message}}</h1>
    <p>How can a great day start ? with a good inspiration</p>
    {%for quo in quote%}
    <p>{{quo.quote}}</p>
    <i>~~{{quo.author}}~~</i>
    {%endfor%}
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="container">

          <div class="bg-text">
            <h1>I am kay</h1>
            <h3>I love music </h3>
          </div>
          </pre>
          <br>
          <hr class="bg-info">
          <h1>Comments....</h1>
          <div class="container">
            <div class="comments">
              {%for comment in commento%}
              <div class="comments card">
                <div class="card-header">

                  <p>{{comment.username}} commented on {{comment.posted}}</p>
                </div>
                <div class="card-body">
                  <p>{{comment.comment}}</p>
                </div>
                <div class="card-footer">

                  {%if current_user.is_authenticated%}
                  <a href="" data-method="delete" data-confirm="Are you sure?">admin online</a>
                  {%endif%}
                </div>
              </div>

              {%endfor%}

            </div>
            <div class="row">

              <div class="col-md-2">

              </div>
              <div class="col-md-8">
                <div class="">
                  <h3>Add a comment</h3>
                  <p class="alert alert-info"><b>By commenting you automatically subscribe to email subscription</b></p>
                  <br>
                  <br>
                  {{wtf.quick_form(comments)}}

                </div>

              </div>
              <div class="col-md-2">

              </div>

            </div>


          </div>
        </div>

      </div>
    
    </div>
  </div>
</div>
{%endblock%}

app/templates/navbar.html
<!--Navbar -->
<nav  class="mb-1 navbar navbar  navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">music</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
     
      {%if current_user.is_authenticated%}
      <li class="nav-item">

        <a class="nav-link" href="{{url_for('main.new_blog')}}">Post A new Blog</a>
      </li>
      {%endif%}
    
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      {%if current_user.is_authenticated%}
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class=""></i>
        </a>
      </li>
      <li class="nav-item avatar dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">{{current_user.username}}
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-secondary"
          aria-labelledby="navbarDropdownMenuLink-55">
          <a class="dropdown-item" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
          <a class="dropdown-item" href="{{url_for('auth.logout')}}">Log Out</a>
          {%else%}
          <a class="dropdown-item" href="{{url_for('auth.login')}}">sign in</a>
          {%endif%}
        </div>
      </li>
    </ul>
  </div>
</nav>

app/templates/new_blog.html
{%extends 'base.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block content%}

<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      {{wtf.quick_form(newBlog)}}
      {{simplemde.load}}
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-4">
      <!-- Card -->
      <div id="bg" class="card testimonial-card">

        <!-- Background color -->
        <div class="card-up indigo lighten-1"></div>

        <!-- Avatar -->
        <div class="avatar mx-auto white">
          {% if user.profile %}
          <img src="{{url_for('static',filename=user.profile)}}" alt="profile avatar" class="rounded-circle">
          {%else%}
          <img src="/static/img/default.svg" alt="profile avatar" class="img-responsive rounded-circle">
          {% endif %}
        </div>

        <!-- Content -->
        <div class="card-body">
          <!-- Name -->
          <h4 class="card-title">{{user.username| capitalize}}</h4>
          <h5>{{user.occupation}}</h5>
          <hr class="default-color">
          <!-- Quotation -->
          <h4>Profile Details</h4>
          {% if user == current_user %}
          <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
          {% endif %}
          <!--Displaying user bio-->
          {% if user.about %}
          <p><i class="fas fa-quote-left"></i>{{user.about}}</p>
          {%else%}
          <p> {{user.username| capitalize}} has no bio </p>
          {% endif %}
        </div>
        <button id="change" class="btn btn-secondary animated fadeIn" type="button" name="button">Change
          Profile</button>
        <div class="profiles animated fadeIn">
          {%if user==current_user%}
          <form class="form-group" action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
            enctype="multipart/form-data">
            <input class="form-control" type="file" name="photo" value="" required>
            <input id="update" class="btn btn-info" type="submit" name="" value="Save">
          </form>
          {%endif%}
        </div>
      </div>
      <!-- Card -->
    </div>
    <div class="col-md-8">
      <h1>My Blog Profile</h1>
      <div class="row">
        <div class="col-md-6">
        </div>
        <div class="col-md-12">
          <div class="no">
          </div>
          <!-- Card -->
          <div class="card card-cascade wider reverse">

            <!-- Card image -->
            <div class="view view-cascade overlay">

              <div class="mask rgba-white-slight"></div>
              <h1 style="text-align:center">Post your blog </h1>
            </div>

            <!-- Card content -->
            <div class="card-body card-body-cascade text-center">

              <!-- Title -->
              <h4 class="card-title">Hello {{current_user.username}} <strong>Create A new Blog Here </strong></h4>
              <!-- Subtitle -->
              <h6 class="font-weight-bold indigo-text py-2"><a href="{{url_for('main.new_blog')}}"><button>
              class="btn default-color" type="button" name="button">Get started Here</button></a></h6>
            </div>
          </div>
          <!-- Card -->
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
{{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/read_blog.html
{%extends 'base.html'%}
{%import "bootstrap/wtf.html" as wtf%}
{%block content%}
<div class="container-fluid">
  {%if current_user.is_authenticated%}
  <div id="jumbo" class="jumbotron bg-dark">
    <h1>{{data}} <code>Admin mode</code></h1>
    <button id="dele" class="btn btn-outline-danger" type="button" name="button">Click here if you want to delete your
      blog</button>
    <div class="del animated fadeIn">
      {{wtf.quick_form(deleform)}}
    </div>
  </div>
  {%endif%}
  <div class="row">
    <div class="col-md-8">
      <div class="jumbo jumbotron">
        <h1 id="tutor">{{data}} Tutorial</h1>
      </div>
      <div class="container">
        <p>{{format_blog|safe}}</p>
        <br>
        <hr class="bg-info">
        <div class="">
          {%for con in blogComment%}
          <div class="comments card">
            <div class="card-header">
              <p>{{con.username}} commented on {{con.posted}}</p>
            </div>
            <div class="card-body">
              <p>{{con.comment}}</p>
            </div>
            <div class="card-footer">
              {%if current_user.is_authenticated%}
              <p>Admin session</p>
              {%endif%}
            </div>
          </div>
          {%endfor%}
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
              <a id="write" class="btn btn-outline-default">Write a comment</a>
              <div class="com">
                <br>
                <br>
                <i class="alert alert-info"><b>Thank you for subscribing</b></i>
                <br>
                <br>
                {{wtf.quick_form(comments)}}
              </div>
            </div>
            <div class="col-md-2">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="fixed" class="col-md-4">
      <h1>Tutorials</h1>
      <hr class="bg-success">
      <ul class="list-group">
        {%for blog in blogs%}
        <li class="list-group-item"><a href="/read_blog/title/{{blog.id}}/">{{blog.title}}</a></li>
        {%endfor%}
      </ul>
    </div>
  </div>
</div>
{%endblock%}